---
bibliography: moneos.bib
---

# Inleiding

Het MONEOS langetermijn monitoring- en onderzoeksprogramma heeft als belangrijkste doelstelling om grensoverschrijdende samenwerking over het beheer en beleid rond het Zeeschelde estuarium en zijn getijderivieren te ondersteunen.
Dit programma staat beschreven in @meire2008.
Het betreft een breed programma waar zowel fysisch-chemische als biologische variabelen worden ingezameld en onderzocht sinds 2008.
Binnen de biologische variabelen kijkt men onder meer naar het macrozoöbenthos (MZB) [@speybroeck2014].
Deze gegevens worden niet alleen gebruikt voor de beoordeling van de draagkracht en het ecologisch functioneren van het Zeeschelde-estuarium, maar ook voor beoordelingen voor de Europese Kaderrichtlijn Water.
Jaarlijks publiceert INBO een datarapport waarin een overzicht staat van de ruwe gegevens, die door INBO worden ingezameld in het kader van MONEOS [e.g. @ryckegem2020].

Sinds 2008, wordt jaarlijks een monitoring gedaan van MZB in de Zeeschelde (dit is de SPATIAL campagne).
In @speybroeck2014 worden ook de historische MZB gegevens besproken die tussen 1999 en 2008 ingezameld werden.
De jaarlijkse campagne houdt rekening met grote verschillen in fysiotopen langsheen het waterlichaam en moet een representatief beeld geven voor de toestand in een bepaald jaar.
Elk jaar worden nieuwe locaties getrokken volgens een gestratificeerde, random steekproef.
Het doel van deze campagne is om de (intertidale) systeembiomassa van MZB in zacht substraat in te schatten.
Deze systeembiomassa is een maat voor de draagkracht van de Zeeschelde (ZS).
Er is een vast criterium voor evaluatie: 30 ton intertidale droge massa moet minstens aanwezig zijn over de hele schelde en er zijn ook enkele subcriteria voor een uniforme verdeling over de hele Zeeschelde.

Parallel met de SPATIAL campagne, loopt er sinds 2018 ook een campagne waarbij MZB bemonsterd wordt op vaste locaties die gelegen zijn langsheen raaien (transecten) loodrecht op de rivieras in de intertidale zone.
Deze vaste locaties langsheen raaien laten in principe beter toe om een antwoord te geven op vragen zoals "Welke effecten hebben sedimenthoogteveranderingen (door verdieping van de Schelde) op samenstelling en densiteit van MZB?".
Deze raaien zijn gericht gekozen in de ecologisch interessantste gebieden met een intakte slibplaat.
Deze wijziging in strategie vormt een terugkeer naar de manier van werken van vóór 2008, waar er ook met vaste raaien werd gewerkt [@speybroeck2014].

De gecombineerde inspanning om zowel MZB te bemonsteren in de SPATIAL campagne als de RAAIEN campagne is groot.
De vraag stelt zich dan ook of er een optimalisatie mogelijk is van de veldwerkcampagnes zonder dat hiervoor een te grote afbreuk wordt gedaan aan de invulling van de verschillende doelstellingen van deze campagnes.

In dit rapport behandelen we de volgende **vraagstellingen**:

-   Is het steekproefontwerp (steekproefgrootte, stratificatie, randomisatieprocedure) van de SPATIAL campagne voldoende om robuuste uitspraken te kunnen doen over de toestand van de systeembiomassa? De jaarlijks berekende schatting van de systeembiomassa wordt tot nu toe gerapporteerd zonder foutenmarge. Deze foutenmarge is echter nodig om statistisch onderbouwde uitspraken te kunnen doen over de draagkracht van de Zeeschelde (aftoetsing ten opzichte van drempelwaarde van 30 ton).
-   Is het mogelijk om de systeembiomassa in te schatten waarbij zo veel mogelijk gegevens afkomstig van vaste raaien worden gebruikt aangevuld met een beperkte SPATIAL campagne?
-   Voor het stratified random sample moeten veel ecologisch gezien oninteressante gebieden meegenomen worden, waar vogels nauwelijks of niet foerageren (MZB als voedselbron). Zijn deze gebieden dan nodig voor de berekening van de draagkracht van de rivier?

```{=html}
<!--
To do (frank/Joost) Alle achtergrondliteratuur samen zetten Data (google sheets) delen.
Berekening eindcijfer uitschrijven / script / ... Kaartmaterialen / shapefiles / rasters zijn op schaal van een vierkante meter.

-->
```

