---
bibliography: moneos.bib
---

# Discussie

## Onzekerheid op de totale MZB biomassa

Hoe groot is de onzekerheid op de totale MZB biomassa?
Om deze vraag te beantwoorden kijken we vooral naar de spatial survey campagnes, aangezien deze specifiek hiervoor ontworpen zijn.
Door de random gestratificeerde steekproef zal het betrouwbaarheidsinterval met 95% zekerheid het werkelijke tonnage bevatten.
Op niveau van het volledige systeem komen de breedtes van de betrouwbaarheidsintervallen vrij goed overeen tussen de verschillende methodes.
Het gaat om een relatieve foutenmarge tussen 34% en 39% (halve breedte van het betrouwbaarheidsinterval gedeeld door de locatieschatter).
Dit is een aanvaardbare foutenmarge om de vergelijking te maken met de doelstelling van 30 ton.
De steekproefgrootte vergroten zal pas een substantieel effect hebben bij een heel sterke toename van de steekproefgrootte (x 4 geeft een halvering van de foutenmarge).

Indien we per saliniteitszone naar de betrouwbaarheidsintervallen kijken, zien we uiteraard een minder gunstig beeld (want kleinere steekproefgrootte).
In dat geval vinden we relatieve foutenmarges tussen 46% en 157%.

Naast vergroten van de steekproefgrootte, zijn er ook andere opties om de precisie te vergroten.
We bespreken eerst de allocatie van de steekproefgrootte over de strata, daarna wijzigen van de bemonsteringsinspanning en tot slot mogelijkheden in verband met de analyse van de data.

Een eerste optie die we bekeken hebben was nagaan of er een betere allocatie van de steekproef over de verschillende strata mogelijk was (Sectie \@ref(allocatie-strata)).
Hieruit bleek dat het verschil in veldwerkinspanning tussen de raaien en de spatial survey niet groot is ten opzichte van de effecten van variabiliteit en oppervlakte van elk stratum.
Hierdoor was de allocatie voor aantal locaties over de verschillende strata dezelfde voor raaien en spatial.
Belangrijker is echter dat er vrij grote verschillen in optimale allocatie tussen de jaren aan het licht kwamen die te maken hadden met zowel onzekerheid over de stratum-varianties als jaar-tot-jaar veranderingen in de stratum-varianties door dynamiek van onder andere slibruimingen.
Het feit dat deze optimale allocaties van jaar tot jaar kunnen verschillen en dat we op voorhand niet weten hoe de dynamiek zal veranderen, maakt dat we niet 100% kunnen vertrouwen op deze "optimale" allocatie en ze in de praktijk niet bruikbaar is.
We besluiten dan ook dat de huidige manier van alloceren best aangehouden wordt.

Een tweede mogelijkheid is wijzigingen maken aan de verdeling van de inspanning tussen selectie, bemonstering en naverwerking van de stalen in het labo (Sectie \@ref(bemonsteringsinspanning)).
We hebben echter maar gedeeltelijk zicht op de benodigde informatie (kosten en varianties) om hier volledig onderbouwde uitspraken over te doen.
De kosten (weliswaar onvolledig) gaven aan dat de bemonsteringskost de kleinste fractie is van de kosten (10% à 15%), gevolgd door de selectiekost (15% à 25%).
Het resterende en grootste deel zijn de labokosten waarbij de triage van de soorten het grootste aandeel inneemt (iets meer dan 50%).
De triage en determinatie zijn strikt genomen niet noodzakelijk voor de biomassabepaling, maar wel voor andere doeleinden.
Als we triage en determinatie buiten beschouwing laten, is de verdeling evenwichtiger (voor de spatial survey ruwweg 25% bemonstering, 45% selectie, 30% labowerk).
In plaats van meer locaties te bemonsteren, is het misschien beter om meer inspanning ter plaatse te doen.
Indien er een grotere bodemoppervlakte per locatie wordt bemonsterd, krijg je een soort smoother-effect: de schatter op die locatie is preciezer.
Afhankelijk hoe je locatie definieert, zal dit $\sigma_P$ verkleinen ofwel $\sigma_B$ (het zijn een soort van communicerende vaten).
Momenteel is locatie gedefinieerd als een oppervlakte van `r round(opp_per_staal_m2 * 1e4)` cm² met geassocieerde $\sigma_B = 0$ (we hebben de volledige oppervlakte van de locatie bemonsterd en er is dus geen variabiliteit over indien we oppervlakte bemonsterd beschouwen als de voornaamste bron van bemonsteringsinspanning).
Stel dat we nog steeds één bodemstaal nemen maar een bodemboor gebruiken met dubbel zo grote diameter.
De locatie wordt dan geherdefinieerd als een vier keer grotere oppervlakte van `r 4 * round(opp_per_staal_m2 * 1e4)` cm² en dit zal $\sigma_P$ verkleinen.
Stel nu echter dat we een locatie expliciet definiëren als 1 m x 1 m.
In dat geval leggen we $\sigma_P > 0$ vast.
De beste inschatting van biomassa op deze locatie zullen we krijgen indien we de volledige oppervlakte afgraven, zeven, drogen en het asvrij drooggewicht bepalen ($\sigma_B = 0$).
Dit vergt echter een te grote inspanning.
Aan het andere uiteinde van het spectrum zit de huidige manier van werken waarbij één bodemstaal genomen wordt met oppervlakte `r round(opp_per_staal_m2 * 1e4)` cm².
Dit zal een benadering geven van de biomassa binnen de locatie van 1 m x 1 m.
Hoe goed deze benadering is zal er van afhangen hoe homogeen de biomassa lokaal verdeeld is ($\sigma_{B, S=1} > 0$).
Een betere benadering kunnen we altijd bekomen door meerdere kleine bodemstalen te nemen binnen deze locatie ($S > 1$) en ze te poolen (een mengstaal maken; de substalen apart houden zou de kosten sterk opdrijven) ($\sigma_{B, S=1} > \sigma_{B, S>1} > 0$).
Gegeven een definitie van locatie, kunnen we dus met twee variabelen spelen om een zo goed mogelijke kostenbatenbalans te krijgen voor de bemonsteringsinspanning per locatie: het aantal substalen en de oppervlakte per (sub)staal.
Deze mogelijkheid kan haalbaar zijn indien de stalen op een andere manier verwerkt worden.
Momenteel wordt het volledige bodemstaal bewaard door toevoeging van bewaarmiddel.
Een alternatieve methode is om de stalen ter plaatse te zeven met Scheldewater in plaats van achteraf in het labo (mond. med. Frank Van de Meutter).

Ook zonder aanpassingen aan het steekproefontwerp zijn er mogelijkheden om met deze relatief brede foutenmarges om te gaan.
Indien bijvoorbeeld de besluitvorming niet op één jaar gegevens gebaseerd wordt, maar op basis van een lopend gemiddelde van de afgelopen twee of drie jaar.
Daardoor kan er gerapporteerd worden op basis van meer gegevens en zal de foutenvlag kleiner zijn.

## Gebruik van raaien om totale MZB biomassa te schatten

Kan een betrouwbare schatting van de totale MZB biomassa bekomen worden op basis van de raaien of (een deel van) de raaien aangevuld met random gestratificeerde steekproef?

Bij de vergelijking van raaien met spatial survey was vooral het jaar 2019 opvallend verschillend en dan met name veroorzaakt door een veel groter biomassa-aandeel ingeschat door de raaien in middelhoge slikzone van zones met een sterke saliniteitsgradiënt (wat meteen ook de grootste oppervlakte is in het systeem).
De raaien liggen op plaatsen met mooi ontwikkeld slik terwijl bij de spatial survey in elk stratum een vergelijkbaar aantal locaties getrokken worden en er ook locaties getrokken worden met breuksteen.

Met de informatie die we nu hebben, kunnen de raaien niet gebruikt worden om een betrouwbare inschatting te maken.
De poststratificatie die we nu toepassen is enkel gebaseerd op de originele stratificatie door KRW zones in combinatie met ecotopen.
Dit betekent dat met enkel de raaien we veel kans hebben op een overschatting van de werkelijke biomassa in het systeem, omdat de raaien gelegen zijn in de best ontwikkelde zones terwijl we de steekproefschattingen aandikken met de volledige stratum-oppervlaktes (ongeacht of deze goed of slecht ontwikkeld zijn) om tot totalen te komen voor de volledige doelpopulatie.
Aangezien er geen duidelijke ruimtelijke afbakening is van wat de ecologisch beste gebieden zijn, kunnen we deze ontbrekende informatie niet gebruiken om tot betere poststratificatie correcties te komen van de raaien.
Wat er nodig is, is dus een gekende of gemodelleerde kaart of databron die een duidelijke relatie vertoont met "ecologisch beste gebieden".
Dit is echter een beetje een *Catch-22* probleem, want het zijn net de MZB gegevens die men dacht te gebruiken om te bepalen welke gebieden ecologisch best ontwikkeld zijn.
Niettemin kan gewoon op basis van een aantal ecologische overwegingen een operationele definitie bepaald worden die via een GIS-analyse kan afgebakend worden (pers. med. Frank van De Meutter):

-   ononderbroken intertidale zone (niet onderbroken door hard substraat)
-   geen extreem steile gradiënt van laag naar hoge slikzone
-   voldoende brede zone (exacte breedte te bepalen, mogelijk afhankelijk van Saliniteitszone)
-   over een voldoende aaneengesloten lengte aanwezig (exacte lengte te bepalen, mogelijk afhankelijk van Saliniteitszone)

Zo'n kaart kan vervolgens ingedeeld worden in strata (lage, gemiddelde, hoge abundanties) en gebruikt worden in de poststratificatiestap samen met de andere stratificatievariabelen.
Indien er onzekerheid geassocieerd is met zulke kaart, dient bovendien deze onzekerheid via foutenpropagatie mee doorgerekend te worden.
Mogelijk kan dit toelaten om een meer getrouwe afspiegeling te maken van het aandeel biomassa bekomen via de raaien in de doelpopulatie.
Los daarvan, zullen met enkel de raaien veel poststratificatiecellen leeg zijn of weinig data bevatten.
Een aanvulling met extra, aselecte gegevens blijft dus zeker nodig.

## Is een sample in ecologisch oninteressante gebieden nodig?

Voor het stratified random sample moeten veel ecologisch gezien oninteressante gebieden meegenomen worden, waar vogels nauwelijks of niet foerageren (MZB als voedselbron).
Zijn deze gebieden dan nodig voor de berekening van de draagkracht van de rivier?

Vooraleer we hierop antwoorden, is het zinvol een onderscheid te maken tussen de slikzones en de zones met hard substraat.
Binnen de slikzones zijn er verschillen in ecologische kwaliteit van de gebieden, maar bij de zones met hard substraat is de hoeveelheid slik (of de afwezigheid ervan) de primaire beperkende factor.

Bij de berekening van de locatieschatters en de betrouwbaarheidsintervallen wordt wellicht onvoldoende rekening gehouden met de manier waarop hard substraat gesampled wordt.
Als er in praktijk een random punt is met breuksteen, wordt het punt verlegd naar een plaats nabij waar er toch wat slik ligt.
Dit betekent dat de doelpopulatie voor dat stratum in feite slaat op enkel de beperkte oppervlakte aan slik die nog aanwezig is tussen de harde substraten, terwijl bij de berekening de volledige oppervlakte wordt meegeteld.
De biomassabijdrage voor het hard substraat bedraagt, op deze manier berekend, iets meer dan 5% van de totale biomassa (terwijl de oppervlakte hard substraat 1.7 km² beslaat ten opzichte van een totaal van 8.4 km² of 20%) en heeft dus weinig invloed op het uiteindelijke resultaat (maar misschien net nog niet verwaarloosbaar).
Deze manier van berekenen geeft echter een overschatting (vertekening) van de biomassa MZB in hard substraat (op het hard substraat zelf is de biomassa per definitie 0).
Indien men kan inschatten wat het oppervlakte-aandeel is van hard substraat waar er effectief nog slik aanwezig is, kan men de bijdrage van hard substraat opnieuw berekenen.
Als daaruit zou blijken dat deze biomassa-bijdrage heel klein is ten opzichte van het totaal (ook per saliniteitszone), dan is het wellicht beter om dit stratum volledig uit de doelpopulatie te halen en niet meer te samplen.
Nog een andere manier om tot correcte schatting voor hard substraat te komen is om de random punten met breuksteen *niet* te verleggen.
Men dient dan enkel te noteren dat het breuksteen is en geen staal van MZB genomen kon worden (de biomassa is dan 0 voor die locatie).

Wat de overige slikzones betreft (laag, middelhoog en hoog), blijft het nodig om in elk van deze strata locaties te bemonsteren opdat een goed gemiddeld beeld kan bekomen worden voor de berekening van de draagkracht van de rivier.

## Is een alternatief meetnetontwerp een optie?

Tot slot hebben we een mogelijkheid verkend die zou kunnen toelaten om enerzijds een representatief beeld te krijgen van de draagkracht van het systeem en anderzijds ook beter toelaat om vragen te beantwoorden die men beoogt met het systeem van raaien (zoals effecten van sedimenthoogteveranderingen op MZB biomassa en samenstelling).

Allocatie van de steekproefgrootte...

Mogelijke alternatieven:

1.  Een ruimtelijk gebalanceerde trekking in elk stratum

-   jaarlijkse steekproefgrootte x 2 of x 3

-   trekking zodat punten in volgorde geselecteerd (technisch mogelijk met generalized random tessalation sampling (GRTS), balanced acceptance sampling (BAS), local pivotal method (LPM))

    -   bv 1/2 of 2/3 van de punten beschouwen als permanent vaste punten, overige als jaarlijks random

    -   of alle punten in de populatie een random volgnummer geven (master sample)

        -   jaar 1: set a, b, c; jaar 2: set b, c, d; jaar 3: set c, d, e; etc. zodat in een willekeurig jaar een derde van de punten gedurende drie jaar wordt opgevolgd

2.  Transectgebaseerde, ruimtelijk gebalanceerde aselecte trekking [@foster2020]:

-   in dat geval niet werken met stratificatie volgens ecotoop, maar hoogteligging gebruiken om de richting van transecten te bepalen: enkel volgens toenemende hoogte
-   techniek is echter uitgewerkt voor transecten met vaste lengte, maar de lengte van de raaien en de breedte van de intertidale zone is variabel
-   de inclusiekansen verhogen evenredig met een maat voor het ecologisch potentieel, maar dan hebben we dus opnieuw onafhankelijke gegevens (kaarten, ...) nodig die dit aangeven.
