---
title: "Revisie van het MONEOS macrozoöbenthos meetnet"
author: 
  - firstname: Hans
    name: "Van Calster"
    email: hans.vancalster@inbo.be
    orcid: 0000-0001-8595-8426
  - firstname: Raïsa
    name: Carmen
    email: raisa.carmen@inbo.be
    orcid: 0000-0003-1025-8702
style: INBO
lang: nl
lot: TRUE
lof: TRUE

#colofon
shortauthor: "Van Calster, H. & Carmen, R."
corresponding: hans.vancalster@inbo.be
reviewer:
  - firstname: Frank
    name: "Van de Meutter"
    email: frank.vandemeutter@inbo.be
    orcid: 0000-0002-9850-1860
  - firstname: Joost
    name: "Vanoverbeke"
    email: joost.vanoverbeke@inbo.be
    orcid: 0000-0002-3893-9529
year: 2021
cover_photo:
cover_description:
doi:
reportnr:
depotnr:
embargo:

bibliography: [moneos.bib]
link-citations: TRUE
site: bookdown::bookdown_site

# HTML report specific options. See ?INBOmd::gitbook() for full list and more details.
github-repo: inbo/moneos-benthos-revisie

output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
---

# Voorwoord {.unnumbered}

# Samenvatting {.unnumbered}

De tekst voor de verplichte samenvatting.
Hou het [Heerlijk Helder](https://overheid.vlaanderen.be/communicatie/heerlijk-helder).

# Aanbevelingen voor beheer en/of beleid {.unnumbered}

Verplicht wanneer relevant.

\benglish

# English abstract {.unnumbered}

Insert a translation of the summary here.
\eenglish

```{r renv-restore, eval = FALSE}
renv::restore()
cmdstanr::install_cmdstan(version = "v2.28.0")
```

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  cache = FALSE,
  warning = TRUE,
  error = FALSE,
  message = TRUE
)
library(tidyverse)
library(INBOtheme)
if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}
library(rprojroot)
source(find_root_file("src/utils/utility_functions.R",
                      criterion = is_git_root))
gdrive_data_path <- get_map_data_moneos()
gdrive_gdb_path <- file.path(gdrive_data_path, "GIS/MONEOS.gdb")

library(sf)
library(survey)
library(srvyr)
library(git2rdata)
library(mapview)
mapviewOptions(platform = "leaflet", fgb = FALSE)
library(brms)
library(tidybayes)
library(glmmTMB)
library(gt)
library(terra)
library(spatstat)
```

```{r packages, eval=FALSE}
knitr::write_bib(file = find_root_file(
  "src/rapport/packages.bib",
  criterion = is_git_root
))
```
